services:
  go-web-app:
    pull_policy: always
    restart: always
    image: salmonsalmon/portfolio-yuanyuan:v0.1.6
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=yuanyuanzhou.nl
      - LETSENCRYPT_HOST=yuanyuanzhou.nl
      - SERVER_PORT=80
    volumes:
      - data:/app/data
    ports:
      - "8080:80"

volumes:
  data:
