services:
  go-web-app:
    restart: always
    image: salmonsalmon/portfolio-yuanyuan:v0.0.1
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=yuanyuanzhou.nl
      - LETSENCRYPT_HOST=yuanyuanzhou.nl
    volumes:
      - db_data:/app/data
    ports:
      - "8080:80"

volumes:
  db_data:
